const
    GAME_RESOLUTION = 80,
    CANVAS_WIDTH = 1000,
    CANVAS_HEIGHT = 500,
    BRICK_COLUMN = 20,
    BRICK_ROW = 15,

    BAR_WIDTH = 100,
    BAR_SPEED = 10,
    BAR_HEIGHT = 10,

    BALL_RADIUS = 5,
    BALL_SPEED = 3;

    BRICK_X_ALIGNMENT = 100;
    BRICK_Y_ALIGNMENT = 100;