const
    GAME_SPEED = 80,
    CANVAS_WIDTH = 1000,
    CANVAS_HEIGHT = 500,

    BAR_WIDTH = 100,
    BAR_SPEED = 10,
    BAR_HEIGHT = 10,
    BAR_ACCELERATION_MAX = 20,

    BALL_RADIUS = 5,
    BALL_SPEED = 2,

    BRICK_X_ALIGN = 100,
    BRICK_Y_ALIGN = 100,
    BRICK_COLUMN = 20,
    BRICK_ROW = 15,
    BRICK_HEIGHT = 10;